-- ═══════════════════════════════════════════════════════════════════
-- 반반 BanBan Migration v16 — AI 사용 로그 (유닛 이코노믹스 측정)
--   AI 호출마다 모델·토큰·추정비용 기록 → 학생당 월 비용 집계
-- Supabase SQL Editor에서 실행하세요.
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS ai_usage_log (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    uuid,                              -- 호출한 사용자
    model      text DEFAULT '',                   -- gemini-2.5-flash / claude-haiku-4-5
    feature    text DEFAULT '',                   -- (선택) 어느 기능에서 호출했는지
    in_tokens  int  DEFAULT 0,                    -- 입력 토큰
    out_tokens int  DEFAULT 0,                    -- 출력 토큰
    cost_usd   numeric(12,6) DEFAULT 0,           -- 추정 비용(USD)
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ail_user    ON ai_usage_log (user_id);
CREATE INDEX IF NOT EXISTS idx_ail_created ON ai_usage_log (created_at DESC);

ALTER TABLE ai_usage_log DISABLE ROW LEVEL SECURITY;
GRANT ALL ON ai_usage_log TO anon, authenticated, service_role;
