-- ═══════════════════════════════════════════════════════════════════
-- 반반 BanBan Migration v14 — 시험 요약노트 저장/탐색
--   생성한 요약노트를 저장하고 교과서별로 다시 찾아 출력
-- Supabase SQL Editor에서 실행하세요.
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS cheatsheets (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id     bigint,                          -- 어느 교과서(노트)의 요약인지
    note_title  text  DEFAULT '',
    data        jsonb DEFAULT '{}'::jsonb,        -- AI 생성 요약 데이터(front/back)
    sections    jsonb DEFAULT '[]'::jsonb,        -- 선택한 섹션 목록
    owner_id    uuid,                             -- 생성자 (NULL=공용)
    created_at  text  NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI')
);

CREATE INDEX IF NOT EXISTS idx_cs_note    ON cheatsheets (note_id);
CREATE INDEX IF NOT EXISTS idx_cs_created ON cheatsheets (created_at DESC);

ALTER TABLE cheatsheets DISABLE ROW LEVEL SECURITY;
GRANT ALL ON cheatsheets TO anon, authenticated, service_role;
