-- ═══════════════════════════════════════════════════════════════════
-- 반반 BanBan Migration v15 — Gemini TTS 오디오 캐시
--   같은 텍스트+목소리는 한 번만 생성하고 재사용 (비용·지연 절감)
-- Supabase SQL Editor에서 실행하세요.
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS tts_cache (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       text NOT NULL,                 -- 읽은 텍스트 (단어/문장)
    voice      text NOT NULL DEFAULT 'Kore',  -- 목소리 이름
    audio_b64  text NOT NULL,                 -- WAV → base64
    created_at text NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI')
);

-- 같은 텍스트+목소리 중복 방지 + 조회 가속
CREATE UNIQUE INDEX IF NOT EXISTS idx_tts_text_voice ON tts_cache (text, voice);

ALTER TABLE tts_cache DISABLE ROW LEVEL SECURITY;
GRANT ALL ON tts_cache TO anon, authenticated, service_role;
