-- ═══════════════════════════════════════════════════════════════════
-- 반반 BanBan Migration v11 — 노트 라이브러리 SQLite → Supabase 이전
-- 기존: data/notes.db (로컬 SQLite, 배포 시 휘발) → Supabase 영구 저장
-- Supabase SQL Editor에서 실행하세요.
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS notes (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        text  NOT NULL,
    grade        text  DEFAULT '',
    publisher    text  DEFAULT '',
    author       text  DEFAULT '',
    chapter      text  DEFAULT '',
    content_type text  DEFAULT '',                 -- 단어|대화문|본문|전체
    words        jsonb DEFAULT '[]'::jsonb,        -- [[en, kr], ...]
    dialogues    jsonb DEFAULT '[]'::jsonb,        -- [{title, lines:[[en,kr],...]}, ...]
    text_data    jsonb DEFAULT '{}'::jsonb,        -- {title_en, title_kr, sentences:[[en,kr],...]}
    item_count   int   DEFAULT 0,
    tags         text  DEFAULT '',
    owner_id     uuid,                             -- 향후 선생님별 소유권 (현재 미사용, NULL=공용)
    created_at   text  NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI')
);

-- 목록/필터 조회 가속
CREATE INDEX IF NOT EXISTS idx_notes_grade        ON notes (grade);
CREATE INDEX IF NOT EXISTS idx_notes_publisher    ON notes (publisher);
CREATE INDEX IF NOT EXISTS idx_notes_content_type ON notes (content_type);
CREATE INDEX IF NOT EXISTS idx_notes_created_at   ON notes (created_at DESC);

-- 앱은 anon 키로 접근 → RLS 비활성 + 권한 부여 (기존 테이블들과 동일 정책)
ALTER TABLE notes DISABLE ROW LEVEL SECURITY;
GRANT ALL ON notes TO anon, authenticated, service_role;

-- ───────────────────────────────────────────────────────────────────
-- (선택) 기존 로컬 노트를 id 보존하며 업로드한 경우, 시퀀스 충돌 방지용:
--   migrate_local_notes.py 실행 후 아래를 한 번 실행하세요.
--   SELECT setval(pg_get_serial_sequence('notes','id'),
--                 COALESCE((SELECT MAX(id) FROM notes), 1));
-- ───────────────────────────────────────────────────────────────────
